stages:
- configure
- build
- deploy

configure_job:
    before_script:
    - ./scripts/install-deps.sh
    stage: configure
    script:
    - ./autogen.sh
    - ./configure --enable-firewalld

build_job:
    stage: build
    script:
    - make -j

