stages:
- install-dep
- configure
- build
- deploy

install-dep-job:
    stage: install-dep
    script:
    - ./scripts/install-deps.sh

configure-job:
    stage: configure
    script:
    - ./autogen.sh
    - ./configure --enable-firewalld

build-job:
    stage: build
    script:
    - make -j
