stages:
- install-dep
- build
- deploy

variables:
    INSTALL_DEP_SCRIPT: "echo 'hpcgrid3102' | su root -c ./scripts/install-deps.sh"
    BUILD_SCRIPT: "./autogen.sh && ./configure --enable-firewalld && make -j && echo 'hpcgrid3102' | su root -c 'make install' "
    DEPLOY_SCRIPT: "echo 'hpcgrid3102' | su root -c 'service glusterd start' "

install-dep-00:
    stage: install-dep
    tags:
      - tstore00
    script:
    - sh -c "$INSTALL_DEP_SCRIPT" 

install-dep-01:
    stage: install-dep
    tags:
      - tstore01
    script:
    - sh -c "$INSTALL_DEP_SCRIPT" 

install-dep-02:
    stage: install-dep
    tags:
      - tstore02
    script:
    - sh -c "$INSTALL_DEP_SCRIPT" 

install-dep-03:
    stage: install-dep
    tags:
      - tstore03
    script:
    - sh -c "$INSTALL_DEP_SCRIPT" 

install-dep-04:
    stage: install-dep
    tags:
      - tstore04
    script:
    - sh -c "$INSTALL_DEP_SCRIPT" 

install-dep-05:
    stage: install-dep
    tags:
      - tstore05
    script:
    - sh -c "$INSTALL_DEP_SCRIPT" 

install-dep-06:
    stage: install-dep
    tags:
      - tstore06
    script:
    - sh -c "$INSTALL_DEP_SCRIPT" 

install-dep-07:
    stage: install-dep
    tags:
      - tstore07
    script:
    - sh -c "$INSTALL_DEP_SCRIPT" 

install-dep-08:
    stage: install-dep
    tags:
      - tstore08
    script:
    - sh -c "$INSTALL_DEP_SCRIPT" 

install-dep-09:
    stage: install-dep
    tags:
      - tstore09
    script:
    - sh -c "$INSTALL_DEP_SCRIPT" 

install-dep-10:
    stage: install-dep
    tags:
      - tstore10
    script:
    - sh -c "$INSTALL_DEP_SCRIPT" 

install-dep-11:
    stage: install-dep
    tags:
      - tstore11
    script:
    - sh -c "$INSTALL_DEP_SCRIPT" 

install-dep-12:
    stage: install-dep
    tags:
      - tstore12
    script:
    - sh -c "$INSTALL_DEP_SCRIPT" 

install-dep-13:
    stage: install-dep
    tags:
      - tstore13
    script:
    - sh -c "$INSTALL_DEP_SCRIPT" 

install-dep-14:
    stage: install-dep
    tags:
      - tstore14
    script:
    - sh -c "$INSTALL_DEP_SCRIPT" 

install-dep-15:
    stage: install-dep
    tags:
      - tstore15
    script:
    - sh -c "$INSTALL_DEP_SCRIPT" 

build-00:
    stage: build
    tags:
     - tstore00
    script:
    - sh -c "$BUILD_SCRIPT" 

build-00:
    stage: build
    tags:
     - tstore00
    script:
    - sh -c "$BUILD_SCRIPT" 

build-01:
    stage: build
    tags:
     - tstore01
    script:
    - sh -c "$BUILD_SCRIPT" 

build-02:
    stage: build
    tags:
     - tstore02
    script:
    - sh -c "$BUILD_SCRIPT" 

build-03:
    stage: build
    tags:
     - tstore03
    script:
    - sh -c "$BUILD_SCRIPT" 

build-04:
    stage: build
    tags:
     - tstore04
    script:
    - sh -c "$BUILD_SCRIPT" 

build-05:
    stage: build
    tags:
     - tstore05
    script:
    - sh -c "$BUILD_SCRIPT" 

build-06:
    stage: build
    tags:
     - tstore06
    script:
    - sh -c "$BUILD_SCRIPT" 

build-07:
    stage: build
    tags:
     - tstore07
    script:
    - sh -c "$BUILD_SCRIPT" 

build-08:
    stage: build
    tags:
     - tstore08
    script:
    - sh -c "$BUILD_SCRIPT" 

build-09:
    stage: build
    tags:
     - tstore09
    script:
    - sh -c "$BUILD_SCRIPT" 

build-10:
    stage: build
    tags:
     - tstore10
    script:
    - sh -c "$BUILD_SCRIPT" 

build-11:
    stage: build
    tags:
     - tstore11
    script:
    - sh -c "$BUILD_SCRIPT" 

build-12:
    stage: build
    tags:
     - tstore12
    script:
    - sh -c "$BUILD_SCRIPT" 

build-13:
    stage: build
    tags:
     - tstore13
    script:
    - sh -c "$BUILD_SCRIPT" 

build-14:
    stage: build
    tags:
     - tstore14
    script:
    - sh -c "$BUILD_SCRIPT" 

build-15:
    stage: build
    tags:
     - tstore15
    script:
    - sh -c "$BUILD_SCRIPT" 

deploy-00:
    stage: deploy
    tags:
     - tstore00
    script:
    - sh -c "$DEPLOY_SCRIPT" 

deploy-01:
    stage: deploy
    tags:
     - tstore01
    script:
    - sh -c "$DEPLOY_SCRIPT" 

deploy-02:
    stage: deploy
    tags:
     - tstore02
    script:
    - sh -c "$DEPLOY_SCRIPT" 

deploy-03:
    stage: deploy
    tags:
     - tstore03
    script:
    - sh -c "$DEPLOY_SCRIPT" 

deploy-04:
    stage: deploy
    tags:
     - tstore04
    script:
    - sh -c "$DEPLOY_SCRIPT" 

deploy-05:
    stage: deploy
    tags:
     - tstore05
    script:
    - sh -c "$DEPLOY_SCRIPT" 

deploy-06:
    stage: deploy
    tags:
     - tstore06
    script:
    - sh -c "$DEPLOY_SCRIPT" 

deploy-07:
    stage: deploy
    tags:
     - tstore07
    script:
    - sh -c "$DEPLOY_SCRIPT" 

deploy-08:
    stage: deploy
    tags:
     - tstore08
    script:
    - sh -c "$DEPLOY_SCRIPT" 

deploy-09:
    stage: deploy
    tags:
     - tstore09
    script:
    - sh -c "$DEPLOY_SCRIPT" 

deploy-10:
    stage: deploy
    tags:
     - tstore10
    script:
    - sh -c "$DEPLOY_SCRIPT" 

deploy-11:
    stage: deploy
    tags:
     - tstore11
    script:
    - sh -c "$DEPLOY_SCRIPT" 

deploy-12:
    stage: deploy
    tags:
     - tstore12
    script:
    - sh -c "$DEPLOY_SCRIPT" 

deploy-13:
    stage: deploy
    tags:
     - tstore13
    script:
    - sh -c "$DEPLOY_SCRIPT" 

deploy-14:
    stage: deploy
    tags:
     - tstore14
    script:
    - sh -c "$DEPLOY_SCRIPT" 

deploy-15:
    stage: deploy
    tags:
     - tstore15
    script:
    - sh -c "$DEPLOY_SCRIPT" 

